proxy/proxy/urls.py
from django.contrib import admin
from django.contrib.auth.forms import AuthenticationForm
from django.urls import path, include

from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", include("store.urls")),
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
]

proxy/store/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

from django.contrib.auth import views as auth_views

from .views import SignUpView

app_name = "store"
urlpatterns = [
    path("", views.index, name="index"),
    path("signin/", views.signin, name='signin'),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    path('deposit/', views.deposit, name='deposit'),
    path('products/<int:product_id>/', views.detail_product, name='detailed_product'),
    path('products/buy/<int:product_id>/', views.buy_product, name='buy_product'),
    path('profile', views.profile, name='profile'),
]

proxy/store/models.py
from django.contrib.auth.models import AbstractUser, User
from django.db import models
from django.http import HttpResponse, HttpResponseBadRequest


class InsufficientBalance(Exception):
    def __init__(self, balance: int = 0, expected_amount: int = 0, *, message: str | None = None):
        _message = message or f"Insufficient Balance. Current balance is {balance}. Needs at least {expected_amount}"
        super().__init__(_message)


class CustomUser(AbstractUser):
    balance = models.PositiveIntegerField(default=0)

    def check_balance(self, amount: int):
        """Indicates whether the user has the ability to pay a payment with this amount."""
        return self.balance >= amount

    class Meta(AbstractUser.Meta):
        swappable = "AUTH_USER_MODEL"


class PaymentSides(models.TextChoices):
    Debit = "Debit"
    Credit = "Credit"


class ProductStatus(models.TextChoices):
    Active = "Active"


class Payment(models.Model):
    created_at = models.DateTimeField("date published", auto_now=True)
    user = models.ForeignKey(CustomUser, on_delete=models.PROTECT)
    side = models.TextField(choices=PaymentSides)
    amount = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.side}: {self.amount} ({self.user})"


class Product(models.Model):
    name = models.CharField(max_length=60)
    description = models.CharField(max_length=600)
    customer = models.ForeignKey(CustomUser, on_delete=models.PROTECT)
    status = models.TextField(choices=ProductStatus, default=ProductStatus.Active)
    in_stock = models.PositiveIntegerField(default=0)
    price = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

proxy/store/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.hashers import make_password, check_password
from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView

from .models import CustomUser, Payment, PaymentSides, Product, InsufficientBalance


def index(request):
    all_proxies = Product.objects.all()
    return render(request, "index.html", {"proxies": all_proxies})


def signup(request):
    print(type(request))

    if request.method == "POST":
        # form = UserCreationForm(request.POST)
        # if form.is_valid():
        #     user = form.save()
        #     login(request, user)
        #     return redirect('store/login.html')

        username = request.POST['username']
        password = request.POST['password']
        email = request.POST['email']

        hashed_password = make_password(password)

        CustomUser.objects.create_user(username, email, hashed_password)

        return redirect(reverse('store:signin'))

    return render(request, 'store/register.html')


def signin(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        print(username, password)

        hashed_password = make_password(password)

        user = authenticate(request, username=username, password=password)
        print(user)
        if user is None:
            error_message = "User was not authenticated. Maybe invalid password or username."
            return render(request, "store/login.html", {"error_message": error_message})

        login(request, user)
        return HttpResponse(user)

    return render(request, 'store/login.html')


def recalculate_balance(user_id: str) -> int:
    user = CustomUser.objects.get(pk=user_id)

    all_credit_payments: list[Payment] = Payment.objects.filter(user_id=user_id, side="Credit")
    all_debit_payments: list[Payment] = Payment.objects.filter(user_id=user_id, side="Debit")

    deposit = 0
    withdraw = 0

    for payment in all_credit_payments:
        deposit += payment.amount

    for payment in all_debit_payments:
        withdraw += payment.amount

    balance = deposit - withdraw

    if balance < 0:
        raise InsufficientBalance(balance)

    user.balance = balance
    user.save()

    return balance


def deposit(request):
    if request.method == "POST":
        amount = request.POST["amount"]
        user_id = request.POST["to"]

        print(request.user)

        Payment(side=PaymentSides.Credit, amount=amount, user_id=user_id).save()
        recalculate_balance(user_id)


def detail_product(request, product_id):
    try:
        product = Product.objects.get(pk=product_id)
    except Product.DoesNotExit:
        raise Http404("Product not found")

    return render(request, "store/products/detail.html", {"product": product})


@login_required(login_url="/accounts/login/")
def buy_product(request, product_id):
    if request.method == "POST":
        product = get_object_or_404(Product, pk=product_id)
        user = request.user
        price = product.price

        if not request.user.check_balance(price):
            messages.error(request, f"Insufficient Balance. Needs at least {price}$")

            return redirect(request.META.get('HTTP_REFERER', 'fallback_url'))

        buy_payment = Payment(side=PaymentSides.Debit, amount=price, user_id=user.id)

        product.in_stock -= 1
        product.save()

        buy_payment.save()

        recalculate_balance(user.id)

        messages.success(request, f"Successfully purchased one proxy.")
        return redirect(request.META.get('HTTP_REFERER', 'fallback_url'))
    else:
        return HttpResponse(status=405)


@login_required(login_url="/accounts/login/")
def profile(request):
    return render(request, "store/profile.html")


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = UserCreationForm.Meta.fields


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

proxy/store/templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'style.css' %}">
  <title>{% block title %}Proxy store{% endblock %}</title>
</head>

<body>
  <main>
    <div>
    {% block content %}
    {% endblock %}
    </div>
  </main>
</body>

</html>

proxy/store/templates/index.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}

{% include 'navbar.html' %}

<div class="center-block container">
    <div class="row">
        {% for element in proxies %}
        <div class="col-sm-6 col-md-4 col-lg-3">
            <div style="height: 270px; overflow-y: auto;" class="product-item panel panel-default">
                <div class="panel-heading">
                    <a href="{% url 'store:detailed_product' element.id %}" class="panel-title link" style="cursor: pointer"><strong>{{ element.name }}</strong></a>
                </div>
                <div class="panel-body">
                    <p>{{ element.description }}</p>
                    <p><i>Status</i>: {{ element.status }}</p>
                    <p><i>In stock</i>: {{ element.in_stock }}</p>
                    <p><i>Customer</i>: {{ element.customer }}</p>
                    <p><i>Price</i>: {{ element.price }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<script src=
"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity=
"sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous">
    </script>

{% else %}
<div class="index-form rounded-box">
    <h1 style="color: #333; margin-bottom: 20px">Proxy Store</h1>
    <a style="width: 240px; height: 50px" class="btn btn-default btn-index-form" href="{% url 'login' %}">Log In</a>
    <a style="width: 240px; height: 50px" class="btn btn-default btn-index-form" href="{% url 'store:signup' %}">Register</a>
</div>
{% endif %}
{% endblock %}

proxy/store/templates/messages.html
{% if messages %}
<div class="container">
    {% for message in messages %}
    <div  role="alert" class="alert alert-{{ message.tags }} {{ message.tags }}">
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}

<!--{% if messages %}-->
<!--<ul class="messages">-->
<!--    {% for message in messages %}-->
<!--    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>-->
<!--        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}-->
<!--        {{ message }}-->
<!--    </li>-->
<!--    {% endfor %}-->
<!--</ul>-->
<!--{% endif %}-->

proxy/store/templates/navbar.html
{% if user.is_authenticated %}
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'store:index' %}">
                <span class="glyphicon glyphicon-home"></span>
            </a>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><p class="navbar-text">Hello, {{ user.username }}</p></li>

                <li><p class="navbar-text">Your balance: {{ user.balance }}$</p></li>
            </ul>

            <form class="navbar-form navbar-right" action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <a type="button" class="btn btn-default" aria-label="Profile" href="{% url 'store:profile' %}"
                   style="margin-right: 5px">
                    <span class="glyphicon glyphicon-user"></span>
                </a>
                <button type="submit" class="btn btn-primary">Log Out</button>
            </form>
        </div>
    </div>
</nav>
{% endif %}

proxy/store/templates/store/login.html
<form method="post">
    {% csrf_token %}
    <label>Username:</label>
    <input type="text" name="username" required><br>
    <label>Password:</label>
    <input type="password" name="password" required><br>
    {% if error_message %}<p style="color:red">{{ error_message }}</p>{% endif %}
    <input type="submit" value="Login">
</form>

proxy/store/templates/store/products/detail.html
{% extends "base.html" %}

{% block title %} {{ product.name }} {% endblock %}

{% block content %}

{% include 'navbar.html' %}

{% include 'messages.html' %}

<div class="index-form center-block">
    <ul style="list-style-type: none;">
        <li style="max-width: 550px; max-height: 800px" class="panel panel-default">
            <div class="panel-heading">
                <h4><strong>{{ product.name }}</strong></h4>
            </div>
            <div class="panel-body">
                <p>{{ product.description }}</p>
                <p><i>Status</i>: {{ product.status }}</p>
                <p><i>In stock</i>: {{ product.in_stock }}</p>
                <p><i>Customer</i>: {{ product.customer }}</p>
                <p><i>Price per one</i>: {{ product.price }}</p>
                <form action="{% url 'store:buy_product' product.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" style="display: block; margin: auto" class="btn btn-default btn-index-form">Buy</button>
                </form>
            </div>
        </li>
    </ul>

<!--    {% for error in errors %}-->
<!--    <div>-->
<!--        <p class="lead">{{ error }}</p>-->
<!--    </div>-->
<!--    {% endfor %}-->
</div>

{% endblock %}

proxy/store/templates/store/profile.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}

<div class="index-form center-block">
    <div class="product-item panel panel-default">
        <div class="panel-body">
            <div class="center-block" style="font-size: 35px">
                <span class="glyphicon glyphicon-user"></span>
            </div>

            <p><b>Username</b>: {{ user.username }}</p>
            <p><b>Email</b>: {{ user.email }}</p>
            <p><b>Balance</b>: {{ user.balance }}$</p>

            <form class="center-block" action="{% url 'password_change' %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary btn-index-form">Reset Password</button>
            </form>
        </div>
    </div>

    <a style="font-size: 30px;" href="{% url 'store:index' %}">
        <span class="glyphicon glyphicon-home"></span>
    </a>
</div>

{% endblock %}

proxy/store/templates/store/register.html
<form method="post">
    {% csrf_token %}
    <label>Username:</label>
    <input type="text" name="username" required><br>

    <label>Password:</label>
    <input type="password" name="password" required><br>

    <label>Email:</label>
    <input type="email" name="email" required><br>

    {% if error_message %}<p style="color:red">{{ error_message }}</p>{% endif %}
    <input type="submit" value="Register">
</form>